name = "oshidra-uploader"
account_id = "c6270d2ac0aefb2ca6ce6831cbc9ca30"
main = "src/index.ts"
compatibility_date = "2026-01-02"
route = "https://assets-uploader.oshidra.com/*"

[vars]
PUBLIC_BASE_URL = "https://assets.oshidra.com"
CLOUDFLARE_ACCOUNT_ID = "c6270d2ac0aefb2ca6ce6831cbc9ca30"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "assets"

[env.production]
name = "oshidra-uploader"
route = "https://assets-uploader.oshidra.com/*"

[env.production.vars]
PUBLIC_BASE_URL = "https://assets.oshidra.com"
CLOUDFLARE_ACCOUNT_ID = "c6270d2ac0aefb2ca6ce6831cbc9ca30"

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "assets"
