name = "oshidra-web-router"
main = "src/ip-router.ts"
compatibility_date = "2026-01-02"

account_id = "c6270d2ac0aefb2ca6ce6831cbc9ca30"

[[d1_databases]]
binding = "DB"
database_name = "oshidora-db"
database_id = "1f7de46f-7b0c-4150-ae76-6dd762a23f71"

[env.production]
name = "oshidra-web-router"

[[env.production.d1_databases]]
binding = "DB"
database_name = "oshidora-db"
database_id = "1f7de46f-7b0c-4150-ae76-6dd762a23f71"
remote = true
